/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;


import Controle.DepartamentoDAO;
import controle.EmpresaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Departamento;
import modelo.Empresa;

/**
 *
 * @author Leandro
 */
public class DepartamentoIF extends javax.swing.JInternalFrame {
    Object[] nomes= {"Nome","Empresa"};
    DefaultTableModel modelotab= new DefaultTableModel(new Object[][]{},nomes);

    /**
     * Creates new form DepartamentoIF
     */
    public DepartamentoIF() {
        initComponents();
        carregarEmpresas();
        carregarDepartamentos();
        departamentos.setModel(modelotab);
        del.setVisible(false);
    }
    
    public void carregarEmpresas()
    {
        EmpresaDAO dao= new EmpresaDAO();
        listaempresa.removeAllItems();
        empresa.removeAllItems();
        
        listaempresa.addItem(null);
        empresa.addItem(null);
        for(Empresa e: dao.buscar())
        {
            listaempresa.addItem(e);
            empresa.addItem(e);
        }
    }
    
    
    public void carregarDepartamentos()
    {
        //departamentos.removeAll();
        modelotab.setNumRows(0);
        DepartamentoDAO dao= new DepartamentoDAO();
        
        for(Departamento obj: dao.buscar())
        {
            modelotab.addRow(new Object[]{obj,obj.getEmpresa()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        departamentos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listaempresa = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nomebusca = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empresa = new javax.swing.JComboBox<>();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        del = new javax.swing.JButton();
        nomedep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(125, 34));
        setPreferredSize(new java.awt.Dimension(800, 600));

        departamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        departamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departamentosMouseClicked(evt);
            }
        });
        departamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                departamentosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(departamentos);

        jLabel1.setText("Empresa :");

        listaempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaempresaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Nome:");

        nomebusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomebuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Cadastro de Departamento");

        jLabel4.setText("Nome: ");

        jLabel5.setText("Empresa");

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        del.setText("Excluir");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        nomedep.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(empresa, 0, 180, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nomedep)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jButton1)))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nomedep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar)
                            .addComponent(cancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)
                        .addComponent(del)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
      Departamento obj= new Departamento();
      
      if(departamentos.getSelectedRow() == -1)
      {
          if(empresa.getSelectedItem()!=null)
          {
                obj.setNome(nomedep.getText());
               obj.setEmpresa((Empresa)empresa.getSelectedItem());
               (new DepartamentoDAO()).adicionar(obj);
          }
          else
          {
              JOptionPane.showMessageDialog(null,"Selecionar empresa é obrigatório");
          }
          
         
      }
      else
      { 
          Departamento objSel =(Departamento)modelotab.getValueAt(departamentos.getSelectedRow(),0);
          nomedep.setText(objSel.getNome());
          objSel.setNome(nomedep.getText());
          objSel.setEmpresa((Empresa)empresa.getSelectedItem());
          (new DepartamentoDAO()).editar(objSel);
      }
      del.setVisible(false);
      nomebusca.setText("");
      nomedep.setText("");
      carregarDepartamentos();
      carregarEmpresas();
    }//GEN-LAST:event_salvarActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed

        Departamento objSel =(Departamento)modelotab.getValueAt(departamentos.getSelectedRow(),0);
        int opexc= JOptionPane.showConfirmDialog(rootPane,"Tem certeza qeu deseja excluir o departamento "+objSel.getNome()+"?");
        if(opexc== JOptionPane.YES_OPTION)
        {
            (new DepartamentoDAO()).excluir(objSel);
            carregarEmpresas();
            carregarDepartamentos();
             nomebusca.setText("");
             nomedep.setText("");
        }

    }//GEN-LAST:event_delActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        nomedep.setText("");
        carregarDepartamentos();
        carregarEmpresas();
        del.setVisible(false);
        nomebusca.setText("");
    }//GEN-LAST:event_cancelarActionPerformed

    private void departamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentosMouseClicked
           del.setVisible(true);
          Departamento obj =(Departamento)modelotab.getValueAt(departamentos.getSelectedRow(),0);
          
           nomedep.setText(obj.getNome());
        
         empresa.setSelectedItem(obj.getEmpresa());      
          
   
    }//GEN-LAST:event_departamentosMouseClicked

    private void departamentosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentosKeyReleased
        
        del.setVisible(true);
        Departamento obj =(Departamento)modelotab.getValueAt(departamentos.getSelectedRow(),0);
          
           nomedep.setText(obj.getNome());
        
         empresa.setSelectedItem(obj.getEmpresa());  
    }//GEN-LAST:event_departamentosKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomebuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomebuscaKeyReleased
        String nome=nomebusca.getText();
        DepartamentoDAO dao= new DepartamentoDAO();
        Empresa ob=(Empresa) listaempresa.getSelectedItem();
        modelotab.setNumRows(0);
        departamentos.removeAll();
        if(!nome.isEmpty())
        {
            for(Departamento obj: dao.buscardado(nome))
            {
                modelotab.addRow(new Object[]{obj,obj.getEmpresa()});
            }
        }
        else if(!nome.isEmpty() && ob!=null)
        {
            for(Departamento obj: dao.buscadepemp(nome,ob))
            {
                modelotab.addRow(new Object[]{obj,obj.getEmpresa()});
            }
            
        }
        else if(ob!=null)
        {
            for(Departamento obj: dao.buscarempresa(ob))
            {
             modelotab.addRow(new Object[]{obj,obj.getEmpresa()});
            }
        }
        else
        {
            carregarDepartamentos();
        }
    }//GEN-LAST:event_nomebuscaKeyReleased

    private void listaempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaempresaActionPerformed
        Empresa ob=(Empresa) listaempresa.getSelectedItem();
        String nome=nomebusca.getText();
        DepartamentoDAO dao= new DepartamentoDAO();
        modelotab.setNumRows(0);
        departamentos.removeAll();
        if(ob==null)
        {
          carregarDepartamentos();
        }
        else if(!nome.isEmpty() && ob!=null)
        {
            for(Departamento obj: dao.buscadepemp(nome,ob))
            {
                modelotab.addRow(new Object[]{obj,obj.getEmpresa()});
            }
        }
        else
        {
            for(Departamento obj: dao.buscarempresa(ob))
            {
             modelotab.addRow(new Object[]{obj,obj.getEmpresa()});
            }
        }
    }//GEN-LAST:event_listaempresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton del;
    private javax.swing.JTable departamentos;
    private javax.swing.JComboBox<Empresa> empresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<Empresa> listaempresa;
    private javax.swing.JTextField nomebusca;
    private javax.swing.JTextField nomedep;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
