/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import java.awt.Color;

/**
 *
 * @author Leandro
 */
public class CorF extends javax.swing.JInternalFrame {

    /**
     * Creates new form CorF
     */
    public CorF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpcores = new javax.swing.ButtonGroup();
        ver = new javax.swing.JRadioButton();
        azu = new javax.swing.JRadioButton();
        pre = new javax.swing.JRadioButton();
        verd = new javax.swing.JRadioButton();
        alt = new javax.swing.JButton();

        setClosable(true);

        gpcores.add(ver);
        ver.setSelected(true);
        ver.setText("Vermelho");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        gpcores.add(azu);
        azu.setText("Azul");

        gpcores.add(pre);
        pre.setText("Preto");

        gpcores.add(verd);
        verd.setText("Verde");
        verd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdActionPerformed(evt);
            }
        });

        alt.setText("Alterar Cor de Fundo");
        alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verd)
                    .addComponent(ver)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(azu)
                            .addComponent(pre))
                        .addGap(64, 64, 64)
                        .addComponent(alt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ver)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(azu)
                        .addGap(18, 18, 18)
                        .addComponent(pre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(alt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(verd)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed

    private void verdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verdActionPerformed

    private void altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altActionPerformed
        if(azu.isSelected())
        {
            getContentPane().setBackground(Color.blue);
        }
        else if(ver.isSelected())
        {
            getContentPane().setBackground(Color.red);
        }
        else if(verd.isSelected())
        {
            getContentPane().setBackground(Color.green);
        }
        else
        {
            getContentPane().setBackground(Color.black);
        }
    }//GEN-LAST:event_altActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alt;
    private javax.swing.JRadioButton azu;
    private javax.swing.ButtonGroup gpcores;
    private javax.swing.JRadioButton pre;
    private javax.swing.JRadioButton ver;
    private javax.swing.JRadioButton verd;
    // End of variables declaration//GEN-END:variables
}
